export const BLOCK_TOOLTIPS = {
  HardStrike: {
    label: 'Hard Strike',
    icon: '⚔️',
    category: 'PHYSICAL ATTACK',
    color: '#f97316',
    cost: '~15 battery',
    effect: 'coreImpact - armor/2',
    effectIcon: '💥',
    description: 'Deals physical damage based on your Core Impact minus half the enemy Chassis Armor. Fast and reliable — your bread and butter attack.',
    tip: 'Great opener. Cheap battery cost with consistent damage every turn.',
  },
  HeavyAttack: {
    label: 'Heavy Attack',
    icon: '💥',
    category: 'PHYSICAL ATTACK',
    color: '#f97316',
    cost: '~30 battery',
    effect: 'coreImpact×1.5 - armor/2',
    effectIcon: '💥',
    description: 'Deals 50% more physical damage than Hard Strike but drains your battery fast. Best saved for finishing blows or burst damage windows.',
    tip: 'Pair with high Wattage robots so you can afford to use it repeatedly.',
  },
  PowerSurge: {
    label: 'Power Surge',
    icon: '⚡',
    category: 'SOFTWARE ATTACK',
    color: '#a855f7',
    cost: '~25 battery',
    effect: 'exploitPower - firewall/2',
    effectIcon: '⚡',
    description: 'Bypasses physical armor entirely — deals software damage based on Exploit Power minus half the enemy Firewall. Shreds armored robots.',
    tip: 'Stack Virus Upload first to reduce enemy Firewall, then Power Surge hits much harder.',
  },
  Patch: {
    label: 'Patch',
    icon: '🩹',
    category: 'HEALING',
    color: '#22c55e',
    cost: '~15 battery',
    effect: '+recovery HP',
    effectIcon: '❤️',
    description: 'Runs emergency repair protocols restoring HP equal to your Recovery stat. Cannot exceed max System Integrity.',
    tip: 'Trigger with an IF block at 40-50% HP — waiting until critical is too late.',
  },
  Firewall: {
    label: 'Firewall',
    icon: '🛡️',
    category: 'DEFENSE',
    color: '#3b82f6',
    cost: '~20 battery',
    effect: '+firewallStrength/2',
    effectIcon: '🛡️',
    description: 'Restores your Firewall by half its base value, capped at max. Keeps your software defenses strong against exploit-heavy opponents.',
    tip: 'Use reactively after taking Virus Upload hits to maintain your defense.',
  },
  ArmorPlate: {
    label: 'Armor Plate',
    icon: '🔩',
    category: 'DEFENSE',
    color: '#3b82f6',
    cost: '~20 battery',
    effect: '+chassisArmor/2',
    effectIcon: '🔩',
    description: 'Deploys emergency armor plating restoring physical defense by half its base value. Reduces incoming Hard Strike and Heavy Attack damage.',
    tip: 'Most effective on tanks with high base Chassis Armor to maximize the restored amount.',
  },
  VirusUpload: {
    label: 'Virus Upload',
    icon: '🦠',
    category: 'DEBUFF',
    color: '#a855f7',
    cost: '~25 battery',
    effect: '-exploitPower/3 FW',
    effectIcon: '📉',
    description: 'Injects a viral payload reducing enemy Firewall by a third of your Exploit Power. The debuff persists until removed by System Scan.',
    tip: 'Use early in the fight — lower enemy Firewall makes every Power Surge deal more damage.',
  },
  SystemScan: {
    label: 'System Scan',
    icon: '🔍',
    category: 'UTILITY',
    color: '#8888aa',
    cost: '~8 battery (once)',
    effect: 'removes all debuffs',
    effectIcon: '✅',
    description: 'Initiates a full system diagnostic lasting 2-5 turns. During the scan the robot is defenseless but on completion ALL active debuffs are purged and stats restored to base.',
    tip: 'High risk, high reward — use when heavily debuffed. Watch out for the vulnerability window.',
  },
  CpuStall: {
    label: 'CPU Stall',
    icon: '💤',
    category: 'STALL',
    color: '#444466',
    cost: '0 battery',
    effect: 'nothing',
    effectIcon: '❌',
    description: 'Does absolutely nothing. This happens automatically when your robot runs out of battery or when an IF condition fails with no ELSE branch.',
    tip: "Never add this intentionally — it wastes your turn. Keep Wattage high to avoid it.",
  },
  'IF block': {
    label: 'IF Block',
    icon: '🔀',
    category: 'CONTROL',
    color: '#f59e0b',
    cost: null,
    description: 'Checks a condition once when the pointer reaches this block. If true, executes all actions inside. If false with no ELSE, the robot CPU Stalls for that turn.',
    tip: 'Always pair with an ELSE branch so your robot never wastes a turn stalling.',
  },
  'IF / ELSE block': {
    label: 'IF / ELSE Block',
    icon: '🔀',
    category: 'CONTROL',
    color: '#f59e0b',
    cost: null,
    description: 'Checks a condition once. If true, executes the IF branch. If false, executes the ELSE branch. No turn is ever wasted — always one branch fires.',
    tip: 'The safest control structure. Use IF/ELSE instead of plain IF whenever possible.',
  },
}
