export const BLOCK_TOOLTIPS = {
  HardStrike: {
    label: 'Hard Strike',
    icon: '⚔️',
    category: 'PHYSICAL ATTACK',
    color: '#f97316',
    cost: '~15 battery',
    effect: 'coreImpact - armor/2',
    effectIcon: '💥',
    description: 'Deals physical damage based on your Core Impact minus half the enemy Chassis Armor. Fast and reliable — your bread and butter attack.',
    tip: 'Great opener. Cheap battery cost with consistent damage every turn.',
  },
  HeavyAttack: {
    label: 'Heavy Attack',
    icon: '💥',
    category: 'PHYSICAL ATTACK',
    color: '#f97316',
    cost: '~30 battery',
    effect: 'coreImpact×1.5 - armor/2',
    effectIcon: '💥',
    description: 'Deals 50% more physical damage than Hard Strike but drains your battery fast. Best saved for finishing blows or burst damage windows.',
    tip: 'Pair with high Wattage robots so you can afford to use it repeatedly.',
  },
  PowerSurge: {
    label: 'Power Surge',
    icon: '⚡',
    category: 'SOFTWARE ATTACK',
    color: '#a855f7',
    cost: '~25 battery',
    effect: 'exploitPower - firewall/2',
    effectIcon: '⚡',
    description: 'Bypasses physical armor entirely — deals software damage based on Exploit Power minus half the enemy Firewall. Shreds armored robots.',
    tip: 'Stack Virus Upload first to reduce enemy Firewall, then Power Surge hits much harder.',
  },
  Patch: {
    label: 'Patch',
    icon: '🩹',
    category: 'HEALING',
    color: '#22c55e',
    cost: '~15 battery',
    effect: '+recovery HP',
    effectIcon: '❤️',
    description: 'Runs emergency repair protocols restoring HP equal to your Recovery stat. Cannot exceed max System Integrity.',
    tip: 'Trigger with an IF block at 40-50% HP — waiting until critical is too late.',
  },
  Firewall: {
    label: 'Firewall',
    icon: '🛡️',
    category: 'DEFENSE',
    color: '#3b82f6',
    cost: '~20 battery',
    effect: '+firewallStrength/2',
    effectIcon: '🛡️',
    description: 'Restores your Firewall by half its base value, capped at max. Keeps your software defenses strong against exploit-heavy opponents.',
    tip: 'Use reactively after taking Virus Upload hits to maintain your defense.',
  },
  ArmorPlate: {
    label: 'Armor Plate',
    icon: '🔩',
    category: 'DEFENSE',
    color: '#3b82f6',
    cost: '~20 battery',
    effect: '+chassisArmor/2',
    effectIcon: '🔩',
    description: 'Deploys emergency armor plating restoring physical defense by half its base value. Reduces incoming Hard Strike and Heavy Attack damage.',
    tip: 'Most effective on tanks with high base Chassis Armor to maximize the restored amount.',
  },
  VirusUpload: {
    label: 'Virus Upload',
    icon: '🦠',
    category: 'DEBUFF',
    color: '#a855f7',
    cost: '~25 battery',
    effect: '-exploitPower/3 FW',
    effectIcon: '📉',
    description: 'Injects a viral payload reducing enemy Firewall by a third of your Exploit Power. The debuff persists until removed by System Scan.',
    tip: 'Use early in the fight — lower enemy Firewall makes every Power Surge deal more damage.',
  },
  SystemScan: {
    label: 'System Scan',
    icon: '🔍',
    category: 'UTILITY',
    color: '#8888aa',
    cost: '~8 battery (once)',
    effect: 'removes all debuffs',
    effectIcon: '✅',
    description: 'Initiates a full system diagnostic lasting 2-5 turns. During the scan the robot is defenseless but on completion ALL active debuffs are purged and stats restored to base.',
    tip: 'High risk, high reward — use when heavily debuffed. Watch out for the vulnerability window.',
  },
  BatteryEqualization: {
    label: 'Battery Equalization',
    icon: '⚖️',
    category: 'SUPPORT',
    color: '#22d3ee',
    cost: '50 battery',
    effect: 'avg(myBat-50, enemyBat)',
    effectIcon: '⚡',
    description: 'Drains 50 battery then equalizes both robots to the average of remaining batteries. Punishes battery-hungry opponents while topping yourself up.',
    tip: 'Strongest when your battery is high and the enemy is running low. Can backfire if you are the one who is drained.',
  },
  StackOverflow: {
    label: 'Stack Overflow',
    icon: '☠️',
    category: 'MEGA ATTACK',
    color: '#d946ef',
    cost: '60 battery + 1 stall',
    effect: '3×coreImpact - armor/2',
    effectIcon: '☠️',
    description: 'Unleashes a catastrophic system overflow dealing triple Core Impact damage. The surge overloads your CPU — you are unable to act the following turn.',
    tip: 'Devastating but risky. Make sure you can survive the exposed stall turn. Best used as a finisher.',
  },
  CpuStall: {
    label: 'CPU Stall',
    icon: '💤',
    category: 'STALL',
    color: '#444466',
    cost: '0 battery',
    effect: 'nothing',
    effectIcon: '❌',
    description: 'Does absolutely nothing. This happens automatically when your robot runs out of battery or when an IF condition fails with no ELSE branch.',
    tip: "Never add this intentionally — it wastes your turn. Keep Wattage high to avoid it.",
  },
  'UPDATE variable': {
    label: 'UPDATE Variable',
    icon: '🔄',
    category: 'MEMORY',
    color: '#22c55e',
    cost: null,
    description: 'Modifies an existing variable using an operator (+= -= *= /= %=). You must SET the variable first. UPDATE does not use up a turn.',
    tip: 'Use += to count up, -= to count down, *= to double, %= to cycle through values (e.g. counter %= 3 cycles 0→1→2→0...).',
  },
  'SET variable': {
    label: 'SET Variable',
    icon: '💾',
    category: 'MEMORY',
    color: '#22d3ee',
    cost: null,
    description: 'Creates or updates a variable with a value or expression. Variables persist throughout the battle and can be used in IF conditions. SET does not use up a turn.',
    tip: 'Use SET counter = 0 at the start, then SET counter = counter + 1 inside loops to track how many times something has happened.',
  },
  'REPEAT block': {
    label: 'REPEAT Block',
    icon: '🔁',
    category: 'CONTROL',
    color: '#22d3ee',
    cost: null,
    description: 'Executes the contained actions a fixed number of times (2–5×). Perfect for multi-hit combos or repeated defensive maneuvers without duplicating blocks.',
    tip: 'Wrap with an IF block to conditionally trigger a burst — e.g. REPEAT 3 HardStrike when enemy HP is low.',
  },
  'IF block': {
    label: 'IF Block',
    icon: '🔀',
    category: 'CONTROL',
    color: '#f59e0b',
    cost: null,
    description: 'Checks a condition once on entry. Supports AND/OR for multiple conditions and NOT to invert any check. If false with no ELSE, the robot CPU Stalls for that turn.',
    tip: 'Use AND to require multiple conditions, OR for fallback logic, NOT to invert any check.',
  },
  'IF / ELSE block': {
    label: 'IF / ELSE Block',
    icon: '🔀',
    category: 'CONTROL',
    color: '#f59e0b',
    cost: null,
    description: 'Checks a condition with full AND/OR/NOT support. Supports ELSE IF chains for multi-branch logic. Always executes one branch — never wastes a turn.',
    tip: 'Click "+ ELSE IF" inside the block to add more branches. Evaluated top-to-bottom — first match wins.',
  },
}

export const VARIABLE_DESCRIPTIONS = {
  myHP:          { description: 'Your robot\'s current health. Reaches 0 = defeat.', range: '0 – max System Integrity' },
  enemyHP:       { description: 'Enemy robot\'s current health. Reduce to 0 to win.', range: '0 – enemy System Integrity' },
  myBattery:     { description: 'Your energy level. Every action costs battery — hits 0 = battery defeat.', range: '0 – max Wattage' },
  enemyBattery:  { description: 'Enemy\'s current battery. They lose if it hits 0 too.', range: '0 – enemy Wattage' },
  myArmor:       { description: 'Your physical defense. Reduces damage from Hard Strike and Heavy Attack.', range: '0 – Chassis Armor stat' },
  enemyArmor:    { description: 'Enemy\'s physical armor value. High armor — use Power Surge instead.', range: '0 – enemy Chassis Armor' },
  myFirewall:    { description: 'Your software defense. Reduces damage from Power Surge and Virus Upload.', range: '0 – Firewall Strength stat' },
  enemyFirewall: { description: 'Enemy\'s software firewall. Weaken it with Virus Upload before Power Surging.', range: '0 – enemy Firewall Strength' },
  myHeat:        { description: 'Your accumulated heat/debuff level. High heat reduces stat effectiveness.', range: '0+' },
  enemyHeat:     { description: 'Enemy\'s current heat level. Higher = more vulnerable to follow-up.', range: '0+' },
  turnNumber:    { description: 'Current battle turn. Battles end at turn 200 — highest HP wins.', range: '1 – 200' },
}
